### ISSUE TITLE
Beegonia causes a crash

### ISSUE THREAD

**Issue by ghost** [ForestryMC/MagicBees#22]
The beegonia flower (from magic bees mod) had no textures. It looked like a block with a checkered pattern of black and purple. It also crashed the server a few seconds after being placed.

[crash-2017-07-15_23.57.52-server.txt](https://github.com/ForestryMC/MagicBees/files/1150834/crash-2017-07-15_23.57.52-server.txt)

**Comment by ghost** [comment]
It appears that the crash appears only in multiplayer and is caused by throwing anything near the flower.

**Comment by darkmtbg2** [comment]
Its the same as #16 the newest commit "7ad31c5" (if you know how to build it) only works in a client side game. it crashes servers and makes it impossible to save the game when you first attempt it to open to LAN port. i hope that its fixed soon as i would love to have it on a personal server that would work 100% but he likely know what the issue is
Btw all of the magic bees flower have the issue as soon as its taken serverside

**Comment by ghost** [comment]
Thank you for the info. Since the mod dev knows about this, I'll just close the issue and redirect it to your post.
