### ISSUE TITLE
Beegonia etc not available. MC 1.10.2

### ISSUE THREAD

**Issue by Jobs2k** [ForestryMC/MagicBees#24]
With FTB Beyond (1.10.0) fully working I added Magic Bees (MagicBees-Alpha-3.0.2.jar for MC 1.10).

The Beegonia, Hiveacynth and Hibeescus are not available.
The rest of the Magic Bees mod items appear to be working fine.

I reported this to Botania and was told this is a Magic Bees issue, however I have noticed that other people have submitted issues with them so they must have them. Am I doing something wrong or has the integration been disabled while fixes are being worked on?

**Comment by darkmtbg2** [comment]
in the latest commits the bee flowers are there but there is a issue in the code that only makes them work in a Client side. since paraphrasing of Elecs words is that a function called GetAge only works in a non server setting(LAN and Dedicated). that makes the flowers crash a server as soon as they try to work #16 they are implemented in the newest commit of magic bees but its not a official build as its beyond mod version 3.0.2
