### ISSUE TITLE
[1.10.2]Crash during startup

### ISSUE THREAD

**Issue by SinusoidalC** [ForestryMC/MagicBees#43]
Magic Bees Version: Beta 3.0.4
With Forge Version 12.18.3.2511
ElecCore 1.7.431
Forestry 5.2.7.220
Full Crash-Repo is down here:
http://paste.ubuntu.com/25925664/

**Comment by SethWilliamson** [comment]
Confirmed

## **Works:**
![bees_crash](https://user-images.githubusercontent.com/2601547/32686664-5ef1b320-c65e-11e7-9c07-bfa483556a51.png)

## **Crashes:**
![bees_crash2](https://user-images.githubusercontent.com/2601547/32686665-649d1f44-c65e-11e7-9470-9f4e448ac835.png)

## **Log:**  
fml-client-latest.log
https://paste.ee/p/fb2a6
Expires 2018-05-12

EDIT: I reposted as issue #43 since this one is flagged for an older release. Please merge issues as you see fit. :)

**Comment by SethWilliamson** [comment]
Looks like the error was on ElecCore's end and has been fixed:
https://github.com/Elecs-Mods/ElecCore/issues/122

Pending pull request:
https://github.com/Elecs-Mods/ElecCore/pull/123
