### ISSUE TITLE
Magic Bees not properly propagating Botania flowers

### ISSUE THREAD

**Issue by wrincewind** [ForestryMC/MagicBees#61]
Linking to the relevant Botania bug: https://github.com/Vazkii/Botania/issues/2508 

The long and short version is that Magic Bees with the 'magicbees.alelle.flowersbotania' trait produce errored blocks instead of flowers. 

Additionally, and i'm not sure if it's related to you or what, but all bees with the trait 'Flowers: Flowers' have only been spawning Poppies. These two bugs might have the same root cause? 

I'd assume they're spawning the default flower and not properly writing damage or NBT values. The poppies have a damage value of 0, and the Botania Flower has a damage value of 0 and a single, empty NBT Tag (specifically {type:""}

**Comment by Robijnvogel** [comment]
And https://github.com/Vazkii/Botania/issues/2570

@wrincewind just so you know, the `magicbees.alelle.flowersbotania` listing is probably because of a missing or erroneous language key. It should not typically have anything to do with this issue.

Is this one not related to this issue, by the way?
https://github.com/Vazkii/Botania/issues/2352

**Comment by hron84** [comment]
It's not matter if the language key errored or not and I do not see anything in the opening post that would refer to that. 

But, what the post really say, bees generating improper botania flowers, as if you just cheat in a botania:flower in chat with no NBT key, you will get exactly same that the poster reported. So, the error is Magic Bees when spawning flowers, do not set NBT tags properly. Botania's item/block render highly depends on these NBT tags.
