### ISSUE TITLE
[Request] Thaumcraft 6 Integration

### ISSUE THREAD

**Issue by Rundas01** [ForestryMC/MagicBees#65]
Maybe it's a good idea to add 37 species of bees which produce a comb of every Vis-aspect.
These can be processed in a centrifuge to give a vis-crstal shard and maybe a honeydrop and a beeswax.
4 or 9 of these vis-shards can be processed in a carpenter to form a complete crystal.

This would be similar to TC 4 or 5 where the bees produced a comb which yielded a piece of the magic shards.

**Comment by liach** [comment]
Yeah, thaumcraft 6 is out for 1.12 now.

**Comment by hron84** [comment]
At least, basic vis crystals would be awesome, it could make Thaumcraft can be integrated into a skyblock pack.

**Comment by Elec332** [comment]
I have been holding of on releasing it because it is not fully finished. But after some more thinking & digging I found that most thaumonomicon stuff didn't really fit in with TC6. Instead of holding off until I come up with something to fill the gap I'll release it in its current state.

(Which is everything except the thaumonomicon stuff)

**Comment by Elec332** [comment]
https://www.curseforge.com/minecraft/mc-mods/magic-bees/files/2855061
