### ISSUE TITLE
Empowering bees

### ISSUE THREAD

**Issue by Silfir** [ForestryMC/MagicBees#84]
I'm using Version 2.4.4 of Magic Bees in a modpack put together using Twitch mod launcher. I've never had trouble with the mod before and have an older pack running 2.4.3 that doesn't have this issue. 

The trouble I'm having is that the empowering bees are only growing my node's primal aspects to a maximum of 256 in Ordo, Ignis and Terra and 257 in Perditio, Aqua and Aer. I tried combing through config files to see if there is anything setting a ceiling on them but couldn't find anything. I tried node bullying hoping once that threshold was breached it would resume growth, unfortunately it did not. Bullying is working, quite slowly over a few real time days, but the empowering bees are having no further effect, mostly just replenishing compound aspects removed from the bullied node.

**Comment by Elec332** [comment]
I see they attempted to limit node growth to 255 here: https://github.com/ForestryMC/MagicBees/commit/c796902c91e89557c1eada5498bb041e976d6f3b

However it wasn't implemented properly, which means that there is still always 1 draw, even though the vis of a certain aspect is above 255. The rate at which nodes grow is inversely correlated with the size of the node. So the reason it's going extremely slowly is because your node is huge :)

The fact that the nodes _can_ get bigger than 255 is a bug. But because it's on a very old version and it's not gamebreaking im not going to fix it.

Pull requests with changes for 1.7 might be accepted.
